export const PATTERNS = {
WHITESPACE:   /^[ \t]+/,
NEWLINE:      /^\n/,
COMMENT:      /^//[^\n]/,
NUMBER:       /^-?[0-9]+(.[0-9]+)?/,
STRING:       /^"[^"]"|^'[^']'/,
IDENTIFIER:   /^[a-zA-Z_][a-zA-Z0-9_-]/,
LBRACE:       /^{/,
RBRACE:       /^}/,
LPAREN:       /^(/,
RPAREN:       /^)/,
LBRACKET:     /^[/,
RBRACKET:     /^]/,
COLON:        /^:/,
DOT:          /^./,
COMMA:        /^,/,
ASSIGN:       /^=/,
PLUS:         /^+/,
MINUS:        /^-/,
MULTIPLY:     /^*/,
DIVIDE:       /^//,
POWER:        /^^/,
MODULO:       /^%/,
GT:           /^>/,
LT:           /^</,
GTE:          /^>=/,
LTE:          /^<=/
};
